# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9733534a43b941fde58a1decc2c8a03f96fd5f6874ee4673eae997fcf61220fcbc458b47c40a5d19aba38df8f65ea299b20aa58c077055fe7c9a52b634019d01

test:
  secret_key_base: e49f18ef9c48a4c2abf8e9fa833902a718a265eec5680947a0df2745a71a13e222a0fef983cb99041bdde1d7d016c6d28763bea60542734d79d9a36f169c47e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
